description: >
  This executor is the default executor for the Atlas orb.

parameters:
  tag:
    default: current
    description: >
      Pick a specific cimg/base image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
  resource_class:
    description: Configure the executor resource class
    type: enum
    enum: ["small", "medium", "medium+", "large", "xlarge", "2xlarge", "2xlarge+"]
    default: "medium"

resource_class: << parameters.resource_class >>
docker:
  - image: 'cimg/base:<<parameters.tag>>'
